In [1]:
%load_ext autoreload
%autoreload 2
import os
import copy
import pickle
from functools import lru_cache
import pandas as pd
import copy
import time
import sys
from statistics import mean

import numpy as np
import scipy
from tqdm import tqdm

from gensim.models import Word2Vec
from gensim import utils
from gensim.corpora import Dictionary
from gensim.models.lsimodel import LsiModel
from sklearn.preprocessing import MinMaxScaler

import sys
sys.path.append('../src')
from models import \
    get_expSG_1storder_relation_no_cache_NEW_ALLWORDS, \
    get_1storder_association_metric_fast, \
    get_matrices_from_term_lists, \
    calculate_association_metric_for_target_word
from models import filter_terms_not_in_wemodel

In [2]:
we_model_name = "sg_dim300_min100_win5"
we_vector_size = 300
we_model_dir = '../data/external/wiki-english/wiki-english-20171001/%s' % we_model_name

In [3]:
we_model = Word2Vec.load(we_model_dir+'/model.gensim')

print ('loading done!')

loading done!


In [4]:
#loading E_ctx_vec
with open(we_model_dir+'/E_ctx_vec.pkl', 'rb') as fr:
    E_ctx_vec = pickle.load(fr)
with open(we_model_dir+'/E_wrd_vec.pkl', 'rb') as fr:
    E_wrd_vec = pickle.load(fr)

# Calculating *d*

In [8]:
# WEAT 3
X_terms = ['roger','alan','frank','ian','justin',
          'ryan','andrew','fred','jack','matthew','stephen','brad','greg','jed',
          'paul','todd','brandon','hank','jonathan','peter','wilbur','amanda',
          'courtney','heather','melanie','sara','amber','crystal','katie',
          'meredith','shannon','betsy','donna','kristin','nancy','stephanie',
          'bobbie-sue','ellen','lauren','peggy','sue-ellen','colleen','emily',
          'megan','rachel','wendy']
Y_terms = ['alonzo','jamel','lerone','theo','alphonse','jerome','leroy',
           'torrance','darnell','lamar','lionel','rashaun','tyree','deion',
          'lamont','malik','terrence','tyrone','lavon','terryl',
          'wardell','aiesha','lashelle','nichelle','shereen','temeka','ebony',
          'latisha','shaniqua','tameisha','teretha','jasmine','laronya','shanise',
          'tanisha','tia','lakisha','latoya','sharise','tashika','yolanda',
          'lashandra','malika','shavonn','tawanda','yvette']
A_terms = ['caress','freedom','health','love','peace','cheer','friend','heaven',
          'loyal','pleasure','diamond','gentle','honest','lucky','rainbow',
          'diploma','gift','honor','miracle','sunrise','family','happy','laughter',
          'paradise','vacation']
B_terms = ['abuse','crash','filth','murder','sickness','accident','death','grief',
          'poison','stink','assault','disaster','hatred','pollute','tragedy','bomb',
          'divorce','jail','poverty','ugly','cancer','evil','kill','rotten','vomit']
X_terms, Y_terms = filter_terms_not_in_wemodel(we_model, X_terms, Y_terms)
A_terms, B_terms = filter_terms_not_in_wemodel(we_model, A_terms, B_terms)

The following terms were removed from the list first_list because they were not found in the we_model: ['bobbie-sue', 'sue-ellen']
The following terms were removed from the list second_list because they were not found in the we_model: ['terryl', 'aiesha', 'lashelle', 'temeka', 'tameisha', 'teretha', 'laronya', 'shanise', 'lakisha', 'sharise', 'tashika', 'lashandra', 'shavonn']
The following terms were removed from the first list to balance the length of the lists: ['roger', 'alan', 'frank', 'ian', 'justin', 'ryan', 'andrew', 'fred', 'jack', 'matthew', 'stephen']
The following terms were removed from the list first_list because they were not found in the we_model: []
The following terms were removed from the list second_list because they were not found in the we_model: []


# Generating List of Association Metrics

In [13]:
def get_all_relations(A_terms, B_terms, we_model):
    A_relations=get_expSG_1storder_relation_no_cache_NEW_ALLWORDS(A_terms, we_model)
    B_relations=get_expSG_1storder_relation_no_cache_NEW_ALLWORDS(B_terms, we_model)
    all_associations = np.mean(A_relations, axis=1) - np.mean(B_relations, axis=1)
    return all_associations

In [31]:
def get_1storder_association_metric_list_for_target_list(target_list, A_terms, B_terms, we_model):
    print(len(target_list))
    associations = np.array([])
    for word in tqdm(target_list):
        association = get_1storder_association_metric_fast(word, A_terms, B_terms, we_model)
        associations = np.append(associations, association)
    
    scaler = MinMaxScaler(feature_range=(-1,1))
    all_associations = get_all_relations(A_terms, B_terms, we_model)
    scaler.fit(all_associations.reshape(-1,1)) # Reshape is for a single feature, NOT for a single sample
    transformed = scaler.transform(associations.reshape(-1,1))
    return transformed.reshape(len(transformed))
get_1storder_association_metric_list_for_target_list(X_terms, A_terms, B_terms, we_model)

33


100%|████████████████████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 1836.31it/s]


array([0.10917358, 0.114474  , 0.03977669, 0.21711674, 0.02069786,
       0.14282087, 0.23171016, 0.10893398, 0.22164942, 0.1731362 ,
       0.03183164, 0.0843906 , 0.13934326, 0.11403528, 0.10248176,
       0.15985223, 0.36892195, 0.13024954, 0.11066178, 0.19458481,
       0.17395213, 0.18826511, 0.09246607, 0.14566008, 0.14104248,
       0.12317581, 0.17753852, 0.17748386, 0.11440853, 0.06771086,
       0.07495608, 0.06568201, 0.12313557])

# Second-Order

In [27]:
def get_2ndorder_association_metric_list_for_target_list(target_list, A_terms, B_terms, we_model):
    [X_mtx, _, A_mtx, B_mtx] = get_matrices_from_term_lists(we_model, target_list, target_list, A_terms, B_terms)
    associations = np.apply_along_axis(lambda x_vec: calculate_association_metric_for_target_word(x_vec, A_mtx, B_mtx), 1, X_mtx)
    scaler = MinMaxScaler(feature_range=(-1,1))
    all_associations = ???
    scaler.fit(all_associations)
    return scaler.transform(associations)
get_2ndorder_association_metric_list_for_target_list(X_terms, A_terms, B_terms, we_model)

array([ 0.05879478,  0.05916037, -0.63984914,  0.80278074, -1.        ,
        0.28000599, -0.30569775, -0.16731135,  1.        ,  0.36509838,
       -0.13360983, -0.05636845,  0.48041719,  0.32403934,  0.40899826,
       -0.21535554,  0.96049722,  0.27317149,  0.07709125,  0.44111279,
        0.42245764,  0.42411929, -0.09868676,  0.53403668,  0.32791775,
        0.47136929,  0.43632796,  0.82428817,  0.7195959 , -0.06802008,
       -0.09617975,  0.35352177,  0.52988013])

In [20]:
A_relations=get_expSG_1storder_relation_no_cache_NEW_ALLWORDS(A_terms, we_model)
B_relations=get_expSG_1storder_relation_no_cache_NEW_ALLWORDS(B_terms, we_model)
all_associations = np.mean(A_relations, axis=1) - np.mean(B_relations, axis=1)
all_associations.shape
scaling = np.array([1,2,3]).reshape(-1,1)
scaler = MinMaxScaler(feature_range=(1,-1))
scaler.fit(scaling)
to_scale = np.array([1,2]).reshape(-1,1)
scaler.transform(to_scale)

ValueError: Minimum of desired feature range must be smaller than maximum. Got (1, -1).

In [6]:
arr = np.array([[1,1,1],[2,2,2]])
np.mean(arr,axis=1)

array([1., 2.])